# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent
# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=~/.config/i3/i3blocks/$BLOCK_NAME
separator_block_width=5
markup=none
separator=false

# Find your own networking interfaces by typing
# 'ip link' or 'ifconfig' in a terminal window.
# Yours are probably different than mine!

#my ethernet interface is eno1
#most people is eth0
[iface]
instance=enp0s21f0u3
interval=5
color=#ffffff
label=ETH 

#my wifi interface is wlp2s0
[wifi]
instance=wlp2s0
interval=5
color=#ffffff
label=Wifi:
separator_block_width=5

[network-script]
interface=wlp2s0
interval=1
color=#ffffff
TREAT_UNKNOWN_AS_UP=0

# ########################
# separator_block_width=5
# [spacer]
# separator_block_width=5
# full_text= 
# color=#ffffff
# ########################


# CPU usage
#
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
# [cpu_usage]
# label= CPU
# interval=2
# min_width=CPU: 100.00%
# color=#ffffff


########################
[spacer]
full_text=|
color=#ffffff
########################


# Temperature
#
# Support multiple chips, though lm-sensors.
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
# [temperature]
# label= TEMP
# interval=10
# color=#ffffff


# ########################
# separator_block_width=5
# [spacer]
# separator_block_width=5<p></p>
# full_text= 
# color=#ffffff
# ########################



# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
#[memory]
#label=Mem:
## instance=total
#interval=1
#color=#ffaaaa
#separator_block_width=5

#[spacer]
#separator_block_width=0
#full_text=|
#color=#ffffff
# ########################
# separator_block_width=5
# [spacer]
# separator_block_width=5<p></p>
# full_text= 
# color=#ffffff
# ########################


# Disk usage
#
# The directory defaults to $HOME if the instance is not specified.
# The script may be called with a optional argument to set the alert
# (defaults to 10 for 10%).
[disk]
label=home:
interval=30
color=#aaffaa
separator_block_width=5

# [spacer]
# separator_block_width=0
# full_text=|
# color=#ffffff
# my root / partition
# [disk]
# label=/
# instance=/dev/sda3
# interval=30
# color=#ffffff


# ########################
# separator_block_width=5
# [spacer]
# separator_block_width=5<p></p 
# full_text= 
# color=#ffffff
# ########################



# Battery indicator
#
# The battery instance defaults to 0.
# [battery]
# label=BATT 
# # label= BATT
# # instance=1
# interval=30
# color=#aaaaff


# ########################
# separator_block_width=5
# [spacer]
# separator_block_width=5<p></p>
# full_text= 
# color=#ffffff
# ########################

# [volume]
# label=VOL 
# interval=once
# signal=1
# USE_ALSA_NAME=1
# color=#ffffff
# separator_block_width=5

[spacer]
separator_block_width=0
full_text=|
color=#ffffff

[date]
command=date +"%H:%M:%S %a, %b %d" 
interval=1 
label=
color=#fbf1c7

[spacer]
separator_block_width=0
full_text=|
color=#ffffff

# [monitor_manager]
# command=monitor_manager
# interval=once
#SHOW_ON_OFF=1
#SHOW_NAMES=1
#SHOW_PRIMARY=1
#SHOW_MODE=1
#SHOW_BLANKED=1
#SHOW_DUPLICATE=1
#SHOW_ROTATION=1
#SHOW_REFLECTION=1
#SHOW_BRIGHTNESS=1
#SHOW_BRIGHTNESS_VALUE=0
#SHOW_UP_DOWN=1
#FONT_FAMILY=DejaVu Sans Mono
#FONT_SIZE=11
#CLOSE_TO_BOUNDARY_BUFFER=20

#lightred #fb4934
#red #cc241d
#green #98971a
#lightgreen #b8bb26
#yellow #d79921
#lightyellow #fabd2f
#blue #458588
#purple #b16286
#aqua #ffffff
#

