#!/bin/bash

# curr=$(i3-msg -t get_workspaces | jq '.[]' | jq .num | sort | tail -n 1)
curr=$(i3-msg -t get_workspaces | grep -Eo '"name":"[0-9]+"' | grep -Eo "[0-9]+" | sort -n | tail -n 1)
next=$(( $curr+1 ))
echo $next
i3-msg move container to workspace number "$next"
