#!/bin/bash

curr=$(i3-msg -t get_workspaces | grep -Eo '"name":"[0-9]+","visible":true,"focused":true' | grep -Eo "[0-9]+")
all=$(i3-msg -t get_workspaces | grep -Eo '"name":"[0-9]+"' | grep -Eo "[0-9]+")

count=$(echo $all | wc -w)
prev=$(printf "$count\n$all\n$curr" | ~/.i3/switch.out)
echo $prev
i3-msg workspace $prev
